external-secrets:
  priorityClassName: tier-0
  replicaCount: 2
  concurrent: 8
  extraArgs:
    client-qps: 50
    client-burst: 100
#    log.level: debug
  installCRDs: true
  leaderElect: true
  rbac:
    create: true
  serviceAccount:
    name: "external-secrets"
  podDisruptionBudget:
    enabled: true
    maxUnavailable: 25%
    minAvailable: 0
  resources:
    requests:
      cpu: 4
      memory: 512Mi
    limits:
      cpu: 8
      memory: 1Gi
  revisionHistoryLimit: 2
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  nodeSelector:
    role.node.kubernetes.io/critical-addon: "true"
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "topology.kubernetes.io/zone"
      whenUnsatisfiable: DoNotSchedule
      matchLabelKeys:
        - pod-template-hash
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: external-secrets
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: ScheduleAnyway
      matchLabelKeys:
        - pod-template-hash
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: external-secrets
  webhook:
    replicaCount: 2
    revisionHistoryLimit: 2
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    nodeSelector:
      role.node.kubernetes.io/critical-addon: "true"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: DoNotSchedule
        matchLabelKeys:
          - pod-template-hash
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: external-secrets-webhook
      - maxSkew: 1
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: ScheduleAnyway
        matchLabelKeys:
          - pod-template-hash
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: external-secrets-webhook
  certController:
    tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    nodeSelector:
      role.node.kubernetes.io/critical-addon: "true"
    revisionHistoryLimit: 2
