apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ..

helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: external-secrets
  valuesFile: values.yaml
  includeCRDs: true
